import {
  pgTable, uuid, text, integer, timestamp, date, check
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { incidentStatusEnum } from './enums';
import { users } from './users';
import { incidentCategories } from './incident-categories';

export const incidents = pgTable('incidents', {
  id: uuid('id').primaryKey().defaultRandom(),
  referenceNumber: text('reference_number').notNull().unique(), // auto-generated by trigger
  agentId: uuid('agent_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  categoryId: uuid('category_id').notNull().references(() => incidentCategories.id, { onDelete: 'restrict' }),
  incidentDate: date('incident_date').notNull(), // BRD §8: stored independently
  submissionDate: timestamp('submission_date', { withTimezone: true }).notNull().defaultNow(),
  lostMinutes: integer('lost_minutes').notNull(), // CHECK > 0 enforced in SQL migration
  notes: text('notes'), // optional
  status: incidentStatusEnum('status').notNull().default('submitted'),
  reviewedBy: uuid('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewComment: text('review_comment'), // mandatory on rejection (CHECK in SQL migration)
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  lostMinutesPositive: check('chk_lost_minutes_positive', sql`${table.lostMinutes} > 0`),
}));

export type Incident = typeof incidents.$inferSelect;
export type NewIncident = typeof incidents.$inferInsert;