import os

files = {
    r"src\db\schema\team-invites.ts": """import { pgTable, uuid, text, timestamp, boolean, integer } from 'drizzle-orm/pg-core';
import { users } from './users';
import { teams } from './teams';

export const teamInvites = pgTable('team_invites', {
  id: uuid('id').primaryKey().defaultRandom(),
  token: text('token').notNull().unique(), // cryptographically secure UUID
  managerId: uuid('manager_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  teamId: uuid('team_id').notNull().references(() => teams.id, { onDelete: 'restrict' }),
  isActive: boolean('is_active').notNull().default(true),
  usageCount: integer('usage_count').notNull().default(0),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(), // 24h from generation
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  // NEVER hard-delete — old tokens remain for audit trail
});

export type TeamInvite = typeof teamInvites.$inferSelect;
export type NewTeamInvite = typeof teamInvites.$inferInsert;""",

    r"src\db\schema\reference-sequences.ts": """import { pgTable, date, integer } from 'drizzle-orm/pg-core';

// Supports atomic EXC-YYYYMMDD-XXXX generation via PostgreSQL trigger
export const referenceNumberSequences = pgTable('reference_number_sequences', {
  dateKey: date('date_key').primaryKey(),
  lastSeq: integer('last_seq').notNull().default(0),
});""",

    r"src\db\schema\incidents.ts": """import {
  pgTable, uuid, text, integer, timestamp, date, check
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { incidentStatusEnum } from './enums';
import { users } from './users';
import { incidentCategories } from './incident-categories';

export const incidents = pgTable('incidents', {
  id: uuid('id').primaryKey().defaultRandom(),
  referenceNumber: text('reference_number').notNull().unique(), // auto-generated by trigger
  agentId: uuid('agent_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  categoryId: uuid('category_id').notNull().references(() => incidentCategories.id, { onDelete: 'restrict' }),
  incidentDate: date('incident_date').notNull(), // BRD §8: stored independently
  submissionDate: timestamp('submission_date', { withTimezone: true }).notNull().defaultNow(),
  lostMinutes: integer('lost_minutes').notNull(), // CHECK > 0 enforced in SQL migration
  notes: text('notes'), // optional
  status: incidentStatusEnum('status').notNull().default('submitted'),
  reviewedBy: uuid('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewComment: text('review_comment'), // mandatory on rejection (CHECK in SQL migration)
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  lostMinutesPositive: check('chk_lost_minutes_positive', sql`${table.lostMinutes} > 0`),
}));

export type Incident = typeof incidents.$inferSelect;
export type NewIncident = typeof incidents.$inferInsert;""",

    r"src\db\schema\compensation-records.ts": """import {
  pgTable, uuid, text, integer, timestamp, date, check
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { compensationStatusEnum } from './enums';
import { users } from './users';
import { incidents } from './incidents';

export const compensationRecords = pgTable('compensation_records', {
  id: uuid('id').primaryKey().defaultRandom(),
  incidentId: uuid('incident_id').notNull().references(() => incidents.id, { onDelete: 'restrict' }),
  referenceNumber: text('reference_number').notNull(), // synced from parent incident via trigger
  agentId: uuid('agent_id').notNull().references(() => users.id, { onDelete: 'restrict' }),
  compensationDate: date('compensation_date').notNull(),
  compensationMinutes: integer('compensation_minutes').notNull(), // CHECK > 0 in SQL migration
  status: compensationStatusEnum('status').notNull().default('pending_review'),
  reviewedBy: uuid('reviewed_by').references(() => users.id, { onDelete: 'set null' }),
  reviewedAt: timestamp('reviewed_at', { withTimezone: true }),
  reviewComment: text('review_comment'),
  notes: text('notes'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (table) => ({
  compensationMinutesPositive: check(
    'chk_compensation_minutes_positive',
    sql`${table.compensationMinutes} > 0`
  ),
}));

export type CompensationRecord = typeof compensationRecords.$inferSelect;
export type NewCompensationRecord = typeof compensationRecords.$inferInsert;""",

    r"src\db\schema\audit-logs.ts": """import { pgTable, uuid, text, timestamp, jsonb } from 'drizzle-orm/pg-core';
import { auditActionEnum } from './enums';
import { users } from './users';

export const auditLogs = pgTable('audit_logs', {
  id: uuid('id').primaryKey().defaultRandom(),
  userId: uuid('user_id').references(() => users.id, { onDelete: 'set null' }),
  action: auditActionEnum('action').notNull(),
  entityType: text('entity_type').notNull(), // 'incident' | 'compensation_record' | 'user'
  entityId: uuid('entity_id'),
  referenceNumber: text('reference_number'),
  oldStatus: text('old_status'),
  newStatus: text('new_status'),
  comment: text('comment'),
  metadata: jsonb('metadata'), // IP, UA, extra context
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  // NO deletedAt — audit logs are immutable
});

export type AuditLog = typeof auditLogs.$inferSelect;
export type NewAuditLog = typeof auditLogs.$inferInsert;""",

    r"src\db\schema\notifications.ts": """import { pgTable, uuid, text, boolean, timestamp } from 'drizzle-orm/pg-core';
import { notificationTypeEnum } from './enums';
import { users } from './users';

export const notifications = pgTable('notifications', {
  id: uuid('id').primaryKey().defaultRandom(),
  recipientId: uuid('recipient_id').notNull().references(() => users.id, { onDelete: 'cascade' }),
  type: notificationTypeEnum('type').notNull(),
  title: text('title').notNull(),
  body: text('body').notNull(),
  referenceNumber: text('reference_number'),
  entityId: uuid('entity_id'),
  isRead: boolean('is_read').notNull().default(false),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Notification = typeof notifications.$inferSelect;
export type NewNotification = typeof notifications.$inferInsert;""",

    r"src\db\schema\index.ts": """export * from './enums';
export * from './teams';
export * from './users';
export * from './team-invites';
export * from './incident-categories';
export * from './reference-sequences';
export * from './incidents';
export * from './compensation-records';
export * from './audit-logs';
export * from './notifications';""",

    r"src\db\index.ts": """import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import * as schema from './schema';

if (!process.env.DATABASE_URL) {
  throw new Error('DATABASE_URL environment variable is required');
}

// Use connection pooling (Supabase Transaction Mode pooler)
const client = postgres(process.env.DATABASE_URL, {
  prepare: false, // required for Supabase Transaction Mode pooler
});

export const db = drizzle(client, { schema });
export type DB = typeof db;"""
}

for path, content in files.items():
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
