import ExcelJS from 'exceljs';
import type { ExportDataset } from './data';

/**
 * Builds a professionally formatted Excel workbook matching BRD §33:
 * Exactly 10 columns: Reference Number | Agent | HR ID | Incident Date | Category |
 * Lost Minutes | Compensated Minutes | Remaining Minutes | Compensation Date | Status
 */
export async function generateExcelWorkbook(dataset: ExportDataset): Promise<Buffer> {
  const { rows, metadata } = dataset;
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'Exception Tracker System';
  workbook.created = new Date();

  const worksheet = workbook.addWorksheet('Operational Exceptions', {
    views: [{ state: 'frozen', ySplit: 7 }], // Freeze headers at row 7
  });

  // Enable grid lines
  worksheet.views[0].showGridLines = true;

  // 1. Metadata Header Block (Rows 1 - 5)
  const titleRow = worksheet.addRow([metadata.appName.toUpperCase() + ' — OPERATIONAL REPORT']);
  titleRow.font = { name: 'Calibri', size: 16, bold: true, color: { argb: 'FF0F172A' } };
  worksheet.mergeCells('A1:J1');

  const subtitleRow = worksheet.addRow([metadata.reportTitle]);
  subtitleRow.font = { name: 'Calibri', size: 12, italic: true, bold: true, color: { argb: 'FF334155' } };
  worksheet.mergeCells('A2:J2');

  const metaRow1 = worksheet.addRow([`Generated By: ${metadata.generatedBy}   |   Timestamp: ${metadata.generatedAt}`]);
  metaRow1.font = { name: 'Calibri', size: 10, color: { argb: 'FF64748B' } };
  worksheet.mergeCells('A3:J3');

  const metaRow2 = worksheet.addRow([`Filters: ${metadata.filtersSummary}`]);
  metaRow2.font = { name: 'Calibri', size: 10, color: { argb: 'FF64748B' } };
  worksheet.mergeCells('A4:J4');

  const metaRow3 = worksheet.addRow([
    `Summary: ${metadata.totalRows} records (${metadata.totalIncidents} unique incidents) | Total Lost: ${metadata.totalLostMinutes} mins | Total Compensated: ${metadata.totalCompensatedMinutes} mins | Net Remaining: ${metadata.totalRemainingMinutes} mins`,
  ]);
  metaRow3.font = { name: 'Calibri', size: 10, bold: true, color: { argb: 'FF0F172A' } };
  worksheet.mergeCells('A5:J5');

  // Blank spacer row (Row 6)
  worksheet.addRow([]);

  // 2. Strict 10 Fixed Columns Header (Row 7 - BRD §33)
  const headers = [
    'Reference Number',
    'Agent',
    'HR ID',
    'Incident Date',
    'Category',
    'Lost Minutes',
    'Compensated Minutes',
    'Remaining Minutes',
    'Compensation Date',
    'Status',
  ];

  const headerRow = worksheet.addRow(headers);
  headerRow.height = 26;

  headerRow.eachCell((cell, colNumber) => {
    cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' }, // Deep Navy
    };
    cell.alignment = {
      vertical: 'middle',
      horizontal: colNumber === 1 || colNumber === 3 || colNumber === 4 || colNumber === 9 || colNumber === 10 ? 'center' : [6, 7, 8].includes(colNumber) ? 'right' : 'left',
    };
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF334155' } },
      bottom: { style: 'medium', color: { argb: 'FF334155' } },
      left: { style: 'thin', color: { argb: 'FF334155' } },
      right: { style: 'thin', color: { argb: 'FF334155' } },
    };
  });

  // 3. Data Rows
  const startDataRow = 8;
  rows.forEach((r, idx) => {
    const isEven = idx % 2 === 0;
    const row = worksheet.addRow([
      r.referenceNumber,
      r.agentName,
      r.agentHrId,
      r.incidentDate,
      r.category,
      r.lostMinutes,
      r.compensatedMinutes,
      r.remainingMinutes,
      r.compensationDate || '—',
      r.status,
    ]);

    row.height = 20;

    row.eachCell((cell, colNumber) => {
      cell.font = { name: 'Calibri', size: 10, color: { argb: 'FF1E293B' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFFFFFFF' : 'FFF8FAFC' }, // Zebra striping
      };
      cell.alignment = {
        vertical: 'middle',
        horizontal: colNumber === 1 || colNumber === 3 || colNumber === 4 || colNumber === 9 || colNumber === 10 ? 'center' : [6, 7, 8].includes(colNumber) ? 'right' : 'left',
      };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        bottom: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        left: { style: 'thin', color: { argb: 'FFE2E8F0' } },
        right: { style: 'thin', color: { argb: 'FFE2E8F0' } },
      };

      // Number formatting for minute columns
      if ([6, 7, 8].includes(colNumber)) {
        cell.numFmt = '#,##0';
      }
    });
  });

  const lastDataRow = startDataRow + rows.length - 1;

  // 4. Totals Summary Row
  if (rows.length > 0) {
    const summaryRow = worksheet.addRow([
      'TOTAL SUMMARY',
      '',
      '',
      '',
      '',
      { formula: `SUM(F${startDataRow}:F${lastDataRow})`, result: metadata.totalLostMinutes },
      { formula: `SUM(G${startDataRow}:G${lastDataRow})`, result: metadata.totalCompensatedMinutes },
      { formula: `SUM(H${startDataRow}:H${lastDataRow})`, result: metadata.totalRemainingMinutes },
      '',
      '',
    ]);

    summaryRow.height = 24;
    worksheet.mergeCells(`A${lastDataRow + 1}:E${lastDataRow + 1}`);

    summaryRow.eachCell((cell, colNumber) => {
      cell.font = { name: 'Calibri', size: 11, bold: true, color: { argb: 'FF0F172A' } };
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FFE2E8F0' }, // Slate 200
      };
      cell.border = {
        top: { style: 'medium', color: { argb: 'FF0F172A' } },
        bottom: { style: 'double', color: { argb: 'FF0F172A' } },
        left: { style: 'thin', color: { argb: 'FFCBD5E1' } },
        right: { style: 'thin', color: { argb: 'FFCBD5E1' } },
      };
      if (colNumber === 1) {
        cell.alignment = { vertical: 'middle', horizontal: 'right' };
      } else if ([6, 7, 8].includes(colNumber)) {
        cell.alignment = { vertical: 'middle', horizontal: 'right' };
        cell.numFmt = '#,##0';
      }
    });
  }

  // 5. Automatic Column Widths with Safe Padding
  const minWidths = [20, 22, 14, 15, 24, 15, 20, 18, 18, 20];
  worksheet.columns.forEach((col, idx) => {
    let maxLength = minWidths[idx] || 15;
    col.eachCell?.({ includeEmpty: false }, (cell) => {
      const valStr = cell.value ? cell.value.toString() : '';
      if (valStr.length > maxLength && Number(cell.row) >= 7) {
        maxLength = Math.min(valStr.length + 3, 35);
      }
    });
    col.width = maxLength;
  });

  const buffer = await workbook.xlsx.writeBuffer();
  return Buffer.from(buffer);
}